[package]
name = "sui-bytecode-src-verifier"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
anyhow = { version = "1.0.64", features = ["backtrace"] }
clap = { version = "3.2.17", features = ["derive"] }

sui-types = { path = "../sui-types" }
sui-sdk = { path = "../../crates/sui-sdk" }
sui-framework = { path = "../../crates/sui-framework" }

move-symbol-pool = { git = "https://github.com/move-language/move", rev = "e1e647b73dbd3652aabb2020728a4a517c26e28e" }

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package.workspace = true
workspace-hack = { path = "../workspace-hack"}